"""video updations

Revision ID: 3069929d850f
Revises: e6fb200e43b6
Create Date: 2025-05-13 19:44:09.624197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3069929d850f'
down_revision: Union[str, None] = 'e6fb200e43b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
