"""auto migration

Revision ID: 6e862fd5fb0c
Revises: c9891aafde31
Create Date: 2025-07-11 11:08:48.351065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e862fd5fb0c'
down_revision: Union[str, None] = 'c9891aafde31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('summary_text', sa.Text(), nullable=False))
    op.add_column('summaries', sa.Column('transcript', sa.Text(), nullable=True))
    op.drop_column('summaries', 'summary_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('summary_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('summaries', 'transcript')
    op.drop_column('summaries', 'summary_text')
    # ### end Alembic commands ###
