"""Make calendar_id nullable in meetings

Revision ID: c9891aafde31
Revises: 2ff76e200e82
Create Date: 2025-07-06 22:26:04.173933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9891aafde31'
down_revision: Union[str, None] = '2ff76e200e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'calendar_channels', ['id'])
    op.create_unique_constraint(None, 'calendar_sync_tokens', ['id'])
    op.alter_column('meetings', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'meetings', ['id'])
    op.create_unique_constraint(None, 'recordings', ['id'])
    op.create_unique_constraint(None, 'summaries', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'summaries', type_='unique')
    op.drop_constraint(None, 'recordings', type_='unique')
    op.drop_constraint(None, 'meetings', type_='unique')
    op.alter_column('meetings', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'calendar_sync_tokens', type_='unique')
    op.drop_constraint(None, 'calendar_channels', type_='unique')
    # ### end Alembic commands ###
