"""Fix relationship between User and Meeting

Revision ID: db0ea6804f01
Revises: d879e229bd85
Create Date: 2025-05-13 13:24:39.520815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0ea6804f01'
down_revision: Union[str, None] = 'd879e229bd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meetings', ['id'])
    op.create_unique_constraint(None, 'recordings', ['id'])
    op.create_unique_constraint(None, 'summaries', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'summaries', type_='unique')
    op.drop_constraint(None, 'recordings', type_='unique')
    op.drop_constraint(None, 'meetings', type_='unique')
    # ### end Alembic commands ###
