"""video storage

Revision ID: e6fb200e43b6
Revises: db0ea6804f01
Create Date: 2025-05-13 18:10:03.048384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fb200e43b6'
down_revision: Union[str, None] = 'db0ea6804f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('file_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'recordings', ['file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recordings', type_='unique')
    op.drop_column('recordings', 'file_name')
    # ### end Alembic commands ###
