kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: meetbot

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8030
      - containerPort: 30443
        hostPort: 4430