  apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    name:  selenium-chrome-scaledobject
    namespace: selenium
    labels:
      deploymentName: selenium-chrome-node
    annotations:
      autoscaling.keda.sh/pollingInterval: "5"      
      autoscaling.keda.sh/cooldownPeriod: "30"
  spec:
    minReplicaCount: 1
    maxReplicaCount: 8
    scaleTargetRef:
        name: selenium-node-chrome
    triggers: 
      - type: selenium-grid
        metadata:
          url: 'http://selenium-hub.selenium.svc.cluster.local:4444/graphql'